version: '3.9'

services:
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.5.0
    command: >
      ${INSTANCE_CONNECTION_NAME}
      --credentials-file=/secrets/credentials.json
      --address 0.0.0.0
      --port ${DB_PORT}
    volumes:
      - ${GOOGLE_CREDENTIALS_PATH}:/secrets/credentials.json
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    restart: always

  app-server:
    container_name: app-server
    build:
      context: ./app-server
    env_file:
      - .env
    depends_on:
      - cloudsql-proxy
    ports:
      - "${APP_PORT}:${APP_PORT}"

  ai-server:
    container_name: ai-server
    build:
      context: ./ai-server
    env_file:
      - .env
    depends_on:
      - cloudsql-proxy
      - app-server
    ports:
      - "${AI_PORT1}:${AI_PORT}"
